### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by pascalandy** [ikruglov/slapper#12]
Any instruction about building this app?
My goal is the create a docker image out of it :)

Cheers!

**Comment by ikruglov** [comment]
Hi. You just need to compile it. No dependencies.

**Comment by pascalandy** [comment]
Sorry I don't know how. 

I'm really good at packaging Dockerfile ([per example](https://github.com/knqyf263/trivy/pull/99)) but without a clear instruction on how to install the package, I'm clueless. Thanks!

**Comment by pascalandy** [comment]
I guess it's similar to https://github.com/aktau/github-release#how-to-install

Thank you

**Comment by ikruglov** [comment]
sorry for the long reply. There are several options of how you can install it:
1. as you describe, just do `go get github.com/ikruglov/slapper`
2. clone the repo, and do `go build` in the repo's folder

hope this helps

**Comment by spacemudd** [comment]
Lately changed to this:

`go install github.com/ikruglov/slapper@latest`
