### ISSUE TITLE
histogram legend looks odd with `-minY` and `-maxY`

### ISSUE THREAD

**Issue by dgryski** [ikruglov/slapper#4]
The legend on the histogram doesn't appear to be correctly calculated if I run with `-minY=50ms -maxy=200ms`.  With height=46 I still have entries on the screen from starting from 1ms.

**Comment by ikruglov** [comment]
yeah, -minY is currently broken. I'm preparing a fix

**Comment by ikruglov** [comment]
should be fixed by https://github.com/ikruglov/slapper/commit/50de758df55a18d790901f7c6ab43c1daa69b126
